/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Main {

    public static void main(String[] args) {

        LinkedList linkedList = new LinkedList();

        linkedList.insert("hello");
        linkedList.insert("Name");
        linkedList.insert("Farah");

        //System.out.println(linkedList);
        //System.out.println(linkedList.kthFromEnd(3)
        LinkedList linkedList2 = new LinkedList();
//[hello,Name,Farah]
//[My,is, Jamal]
//[hello my name is  farah jamal]
        linkedList2.insert("My");
        linkedList2.insert("is");
        linkedList2.insert("Jamal");


        LinkedList zipperList=new LinkedList();
        System.out.println(zipperList.zip(linkedList,linkedList2)+"\n");
        //System.out.println(linkedList);
        //System.out.println(linkedList.kthFromEnd(3)

        //linkedList.append("append test");
        //linkedList.insertBefore("love","don't");
        //linkedList.insertAfter("learning","and");
        //linkedList.remove(2);
        //linkedList.kthEnd(1);

//        System.out.println(linkedList.size());
//        System.out.println(linkedList.includes("this"));
//
//        System.out.println(linkedList);

    }

}