/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Main {

    public static void main(String[] args) {

        LinkedList linkedList = new LinkedList();

        linkedList.insert("I");
        linkedList.insert("love");
        linkedList.insert("this");
        linkedList.insert("type");
        linkedList.insert("of");
        linkedList.insert("learning");
        linkedList.append("append test");
        linkedList.insertBefore("love","don't");
        linkedList.insertAfter("learning","and");
        linkedList.remove(2);
        System.out.println(linkedList.size());
        System.out.println(linkedList.includes("this"));

        System.out.println(linkedList);

    }

}