/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    // Driver Code
    public static void main(String[] args)
    {
        int[] arr = { 10, 7, 8, 9, 1, 5 };
        int n = arr.length;
QS quickSort=new QS();
        System.out.println(quickSort.quickSort(arr, 0, n - 1)
        );
        System.out.println("Sorted array: ");
    }
}
