/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import structure.HashTable;

import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

        HashTable<String, Integer> characters = new HashTable<>();
        characters.add("Severus Snap", 1);
        characters.add("Farah", 700);
        characters.add("Marah", 701);

        characters.add("Voldemort", 2);
        characters.add("Luna LoveGod", 3);
        System.out.println(characters.contains("ju"));
        System.out.println(characters.hash("Farah"));
        System.out.println(characters.hash("Marah"));

        System.out.println((characters.toString()));

    }
}
