/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LeftJoin;

import RightJoin.RightJoin;

import java.util.HashMap;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        LeftJoin leftJoin=new LeftJoin();
         RightJoin rightJoin=new RightJoin();
        HashMap<String,String>hLeft=new HashMap<>();
        HashMap<String,String>hRight=new HashMap<>();
hLeft.put("farah","jamal");
        hLeft.put("Severus","Tobias");
        hLeft.put("Harry","James");
        hLeft.put("Ron","Weasley");
        hLeft.put("Ahmad","Ibrahim");

        hRight.put("farah","Mohammad");
        hRight.put("Severus","Snap");
        hRight.put("Harry","Potter");
        hRight.put("Luna","LoveGod");
        hRight.put("Ahmad","Mohammad");


        System.out.println(leftJoin.leftJoin(hLeft,hRight));
        System.out.println(rightJoin.rightJoin(hLeft,hRight));
    }
}
