/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion.Sort;

public class Library {
    public static void main(String[] args) {
        InsertionSortArray insertionSortArray=new InsertionSortArray();
        int arr[]={1,50,98,30,20,2,3,99};
        System.out.println(        insertionSortArray.sort(arr));    }
}
