/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        int[] actual = { 5, 1, 6, 2, 3, 4 };
        MS ms=new MS();
        ms.mergeSort(actual);
        ms.printArray(actual);
    }
}
