/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tree;

import BSTPack.BST;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void canInstantiate(){
        BST<Integer> bst = new BST();

        assertTrue(bst.isEmpty());
    }

    @Test
    public void hasOneNode(){
        BST<Integer> bst = new BST();

        bst.Add(45);
        assertFalse(bst.isEmpty());
    }

    @Test
    public void canAddLiftAndRightNode(){
        BST<Integer> bst = new BST();

        bst.Add(45);
        bst.Add(50);
        bst.Add(43);

        assertEquals(50, bst.getTop().getRight().getData(),"The Method should add to the lift and to the right sides");
    }
    @Test
    public void findMax(){
        BST<Integer> test = new BST();

        test.Add(1200);
        test.Add(30);
        test.Add(2514);

        try {
            assertEquals(2514, test.max(), "The method will return the max value");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
