/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tree;

import BST.BST;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void canInstantiate(){
        BST<Integer> bst = new BST();

        assertTrue(bst.isEmpty());
    }

    @Test
    public void hasOneNode(){
        BST<Integer> bst = new BST();

        bst.Add(45);
        assertFalse(bst.isEmpty());
    }

    @Test
    public void canAddLiftAndRightNode(){
        BST<Integer> bst = new BST();

        bst.Add(45);
        bst.Add(50);
        bst.Add(43);

        assertEquals(50, bst.getTop().getRight().getData(),"The Method should add to the lift and to the right sides");
    } 
}
