/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import graph.structure.Graph;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Graph graph = new Graph();
        graph.addVertix("Pa");

        graph.addVertix("Mo");
        graph.addVertix("Nab");
        graph.addVertix("Ar");
        graph.addVertix("Me");
        graph.addVertix("Nar");

        graph.addEdge("Pa", "Ar");
        graph.addEdge("Ar", "Me");
        graph.addEdge("Ar", "Mo");
        graph.addEdge("Me", "Nar");

        graph.addEdge("Me", "Nab");
        graph.addEdge("Mo", "Me");
        graph.addEdge("Mo", "Nab");


        graph.toString();
        System.out.println(graph.breadthFirst("Pa"));

    }
}
