/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import graph.structure.Graph;

import java.util.Arrays;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Graph graph = new Graph();
        graph.addVertix("A");
        graph.addVertix("B");
        graph.addVertix("C");
        graph.addVertix("D");
        graph.addVertix("F");
        graph.addEdge("A", "B");
        graph.addEdge("A", "D");
        graph.addEdge("B", "C");
        graph.addEdge("D", "C");
        graph.addEdge("B", "F");
        graph.addEdge("D", "F");

        graph.toString();

        graph.getnodes();
        System.out.println(graph.getnodes());

        System.out.println(graph.getAdjVertices());
        graph.getAdjVertices("A");
        System.out.println(graph.getAdjVertices("A"));

        System.out.println(Arrays.asList(graph.getAdjVertices()));
        graph.size();
    }
}
