/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tree;


import BSTPack.BST;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) throws Exception {

        BST<Integer> bst = new BST();
        bst.Add(1);
        bst.Add(15);
        bst.Add(20);
        bst.Add(30);
        bst.Add(1998);
        bst.Add(2);

        System.out.println(bst.max());
        System.out.println(bst.contains(55));
        System.out.println(bst.contains(4));
    }
}
